### ISSUE TITLE
Can't start pymakr on Linux

### ISSUE THREAD

**Issue by maximeborges** [pycom/Pymakr#11]
When starting PyMakr on Archlinux (fully updated to date), I get this message:
```
Python 2.7.13
libpng warning: iCCP: known incorrect sRGB profile
Warning: translation file 'eric6_fr_FR'could not be loaded.
Using default.
BackgroundService listening on: 35163
Traceback (most recent call last):
  File "/usr/share/pymakr/modules/Utilities/BackgroundClient.py", line 193, in <module>
    backgroundClient.run()
  File "/usr/share/pymakr/modules/Utilities/BackgroundClient.py", line 178, in run
    'EXCEPTION', '?', [str(exctype), str(excval), tbinfo])
  File "/usr/share/pymakr/modules/Utilities/BackgroundClient.py", line 81, in __send
    self.connection.sendall(header)                                             
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
```

And the application stop. 
What can I do ?

**Comment by Bajoja** [comment]
Same here on Fedora 25.

![pymkr](https://cloud.githubusercontent.com/assets/10621831/23317392/2c6cb972-fac6-11e6-8104-147940afeb83.png)

**Comment by jellium** [comment]
Likewise when running `/usr/local/bin/pymakr`:
```
Warning: translation file 'qt_en_US'could not be loaded.
Using default.
Warning: translation file 'eric6_en_US'could not be loaded.
Using default.
Warning: translation file 'qscintilla_en_US'could not be loaded.
Using default.
BackgroundService listening on: 33671
Error loading plug-in module: PluginFeedback
invalid syntax (urllib2.py, line 220)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pymakr/Utilities/BackgroundClient.py", line 193, in <module>
    backgroundClient.run()
  File "/usr/lib/python3/dist-packages/pymakr/Utilities/BackgroundClient.py", line 178, in run
    'EXCEPTION', '?', [str(exctype), str(excval), tbinfo])
  File "/usr/lib/python3/dist-packages/pymakr/Utilities/BackgroundClient.py", line 81, in __send
    self.connection.sendall(header)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe

```

**Comment by jellium** [comment]
For what it's worth (i.e. it does not help solving the present issue), [here is a post on the Pycom's forum](https://forum.pycom.io/topic/635/pymakr-time-of-death-09-02/35) stating the end of Pymakr as an IDE.
