### ISSUE TITLE
OSError: [Errno 22] EINVAL

### ISSUE THREAD

**Issue by jirikrepl** [pycom/Pymakr#16]
Hi Ralph,
I have this error today. I am can't to flash all my files.

I am using:
Pymakr: 1.3.2
Atom: 1.27.2

```
Connecting on /dev/tty.usbserial-DQ0056JT...

>>>
Uploading project (flash)...
Not safe booting, disabled in settings

Reading file status
Failed to read project status, uploading all files
Creating dir examples
Creating dir lib
[1/10] Writing file connection_tests.py
[2/10] Writing file lib/OTA.py
[3/10] Writing file lib/mqtt.py
[4/10] Writing file lib/mqtt_core.py
[5/10] Writing file lib/pybytes.py
[6/10] Writing file lib/pybytes_library.py
Upload failed.: OSError: [Errno 22] EINVAL
 Please reboot your device manually.
OKTraceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 22] EINVAL
>OKTraceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 22] EINVAL
>OKTraceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 22] EINVAL
>OK>OKets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff8028,len:8
load:0x3fff8030,len:1728
load:0x4009fa00,len:0
load:0x4009fa00,len:14584
entry 0x400a059c
Pycom MicroPython 1.18.0 [v1.8.6-849-046b350] on 2018-06-01; LoPy4 with ESP32
Type "help()" for more information.
>>>
```

**Comment by jirikrepl** [comment]
OK nevermind:)

Maybe it just fails on outdated expansion board 2.

Works without problem with updated expansion board 3

**Comment by Xykon** [comment]
This is a known issue, can you please try this [branch](https://github.com/pycom/pymakr-atom/tree/develop) to see if it fixes the issue?
