### ISSUE TITLE
File "/usr/share/pymakr/modules/Plugins/REPL/Shell.py", line 607, in __simulateVT100 numChars = int(s[:pos])

### ISSUE THREAD

**Issue by arthurlutz** [pycom/Pymakr#9]
When trying to use the Ctrl-E paste mode, lost the focus, did a reset on the board.

```
Warning:
An unhandled exception occurred. Please report the problem
using the error reporting dialog or via email to <support@pycom.io>.
A log has been written to "/home/arthur/.pymakr/pymakr_error.log".

Error information:
--------------------------------------------------------------------------------
2017-01-24, 22:05:53
--------------------------------------------------------------------------------
<type 'exceptions.ValueError'>: 
invalid literal for int() with base 10: 'A === Traceback (most recent call last): File "<stdin>", line 1 SyntaxError: invalid syntax >>> >>> PYB: soft reboot MicroPython v1.8.6-379-gc44ebac on 2017-01-13; WiPy with ESP32 Type "'
--------------------------------------------------------------------------------
File "/usr/share/pymakr/modules/Plugins/REPL/Shell.py", line 635, in __write
advance = self.__simulateVT100(s[i:])
File "/usr/share/pymakr/modules/Plugins/REPL/Shell.py", line 607, in __simulateVT100
numChars = int(s[:pos])

--------------------------------------------------------------------------------
Version Numbers:
Python 2.7.12
Qt 4.8.7
PyQt 4.11.4
sip 4.18
QScintilla 2.9.1
WebKit 537.21
Pymakr 1.0.0.b8

Platform: linux2
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
--------------------------------------------------------------------------------
Plugins Version Numbers:
PluginAbout 6.1.0
PluginAboutPymakr 1.0.0
PluginCodeStyleChecker 6.1.0
PluginCompletionJedi 1.0.3
PluginEricapi 6.1.0
PluginEricdoc 6.1.0
PluginFeedback 1.0.0
PluginFullUI 1.0.0
PluginLiteUI 1.0.0
PluginPycomDevice 1.0.0
PluginPycomStyle 1.0.0
PluginPycomSync 1.0.0
PluginREPL 1.0.0
PluginSyntaxChecker 6.1.0
PluginTabnanny 6.1.0
PluginUpdate 1.0.0
PluginVcsMercurial 6.1.0
PluginVcsPySvn 6.1.0
PluginVcsSubversion 6.1.0
PluginVmListspace 6.1.0
PluginVmTabview 6.1.0
PluginWizardE5MessageBox 6.1.0
PluginWizardPyRegExp 6.1.0
PluginWizardQColorDialog 6.1.0
PluginWizardQFileDialog 6.1.0
PluginWizardQFontDialog 6.1.0
PluginWizardQInputDialog 6.1.0
PluginWizardQMessageBox 6.1.0
PluginWizardQRegExp 6.1.0
PluginWizardQRegularExpression 6.1.0
--------------------------------------------------------------------------------
Distribution Info:
/etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

/etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by RalphHogenbirk** [comment]
How did you get into paste mode exactly? Pymakr's console doesn't support ctrl-e command.
